### PR TITLE
Deploy of Native Staking

### PR DESCRIPTION
**Pull request by naddison36**
# Change Summary

## LRTDepositPool
* Removed `depositETH` as ETH deposits will be done using `depositAsset` with WETH as the asset.
* Removed `transferETHToNodeDelegator` as `transferAssetToNodeDelegator` will be used with WETH as the asset.
* Removed `getETHDistributionData` as `getAssetDistributionData` with WETH as the asset will be used instead.
* `getAssetDistributionData` changed to read the asset balance from each NodeDelegator.
* Renamed the return params of `getTotalAssetDeposits` to `depositPoolAssets`, `ndcAssets` and `eigenAssets`
* Changed `removeNodeDelegatorContractFromQueue` to read the asset balance from the NodeDelegator
* Removed `receive()` as it no longer be receiving any ETH.

## NodeDelegator
* Added WETH address to constructor so the immutable `WETH_TOKEN_ADDRESS` can be set.
* `transferBackToLRTDepositPool` converts ETH in the NodeDelegator into WETH before transferring WETH to the Deposit Pool
* `getAssetBalance` changed to return assets in the Node Delegator and assets staked in Eigen Layer. This includes staked ETH for the WETH asset. Previously it just returned assets in EigenLayer strategies.
* `getAssetBalances` changed to iterate over `getAssetBalance` using the supported assets. It previously missed assets in the NodeDelegator but not yet in an EigenLayer strategy.
* Removed `getETHEigenPodBalance` and `sendETHFromDepositPoolToNDC` as they are covered with `getAssetBalance` and `transferBackToLRTDepositPool` using WETH as the asset.
* `stakeEth` changed to withdraw ETH from WETH before depositing 32 ETH into a validator via the EigenPod.
* Removed `verifyWithdrawalCredentials` as that is currently paused by EigenLayer on mainnet and changed with the M2 contracts.
* Added `approveSSV` and `depositSSV` to support paying SSV tokens to SSV Operators via the `SSVNetwork` contract.
* Added `registerSsvValidator` to register a new validator in the SSV Cluster with the SSV Operators.

## PrimeZapper
* Utility contract to facilitate ETH deposits into PrimeETH.
* `deposit` takes ETH, converts to WETH and then deposits the WETH into PrimeETH.

## Other contracts
* Added `WETHPriceOracle` that returns 1e18 like OETH

See the following PRs for the full details
* https://github.com/oplabs/primestaked-eth/pull/36
* https://github.com/oplabs/primestaked-eth/pull/35
* https://github.com/oplabs/primestaked-eth/pull/33

# Deployment Summary

* Native Staking `NodeDelegator` implementation [0x7d18405358c52acb3d7c8d2226c1b2e0379c1efd](https://etherscan.io/address/0x7d18405358c52acb3d7c8d2226c1b2e0379c1efd)
* Native Staking `NodeDelegator` proxy [0x18169ee0ced9aa744f3cd01adc6e2eb2e8fb0087](https://etherscan.io/address/0x18169ee0ced9aa744f3cd01adc6e2eb2e8fb0087)
* `LRTDepositPool` implementation [0xC059Ce5a024f25Dc90f2f5C852b4dcc00f316262](https://etherscan.io/address/0xC059Ce5a024f25Dc90f2f5C852b4dcc00f316262)
* LST `NodeDelegator` implementation [0xAC49836f90E37B8Ab7db5de0e5Bec0b1621451F3](https://etherscan.io/address/0xAC49836f90E37B8Ab7db5de0e5Bec0b1621451F3)
* `WETHPriceOracle` implementation [0xd480388103CC1F274e2e45C72C8D5B2F5188a47E](https://etherscan.io/address/0xd480388103CC1F274e2e45C72C8D5B2F5188a47E)
* `WETHPriceOracle` proxy [0x2772337eD6cC93CB440e68607557CfCCC0E6b700](https://etherscan.io/address/0x2772337eD6cC93CB440e68607557CfCCC0E6b700)
* `PrimeZapper` [0x3cf4Db4c59dCB082d1A9719C54dF3c04Db93C6b7](https://etherscan.io/address/0x3cf4Db4c59dCB082d1A9719C54dF3c04Db93C6b7)

# Deployment Plan

- [x] Clean build

```
forge clean
npm run clean
npm run build
```

- [x] Test deploy of new `NodeDelegator` contract

Start a local Anvil node that is a fork of mainnet

```
make node-fork
```

Set `IMPERSONATE` in the `.env` file to the Mainnet Relayer.
Comment out the `DEFENDER_RELAYER_KEY` and `DEFENDER_RELAYER_SECRET` 

```
IMPERSONATE=0x5De069482Ac1DB318082477B7B87D59dfB313f91    # Relayer account
```

Test the Hardhat `deployNodeDelegator` task against the local forked node

```
export DEBUG=prime*
npx hardhat deployNodeDelegator --index 1 --network local
```

- [x] Deploy new `NodeDelegator` contract via the Defender Relayer

Comment out `IMPERSONATE` in the `.env` file to the Mainnet Relayer.

Generate an API key for the `Operations` Defender Relayer.
Set the `DEFENDER_RELAYER_KEY` and `DEFENDER_RELAYER_SECRET` variables in the `.env` file.

Make sure the Defender Relayer's Gas price cap policy is reasonable. eg 80 Gwei

Run the Hardhat `deployNodeDelegator` task against the mainnet
```
export DEBUG=prime*
npx hardhat deployNodeDelegator --index 1 --network mainnet
```

Results:
* Create NodeDelegator tx [0xaa5d3da83dd7b31f7d7e7210ef4f792e5326e47894f3cc310a9a5dfa2f358a1b](https://etherscan.io/tx/0xaa5d3da83dd7b31f7d7e7210ef4f792e5326e47894f3cc310a9a5dfa2f358a1b)
* `NodeDelegator` implementation contract [0x7d18405358c52acb3d7c8d2226c1b2e0379c1efd](https://etherscan.io/address/0x7d18405358c52acb3d7c8d2226c1b2e0379c1efd)
* Create NodeDelegator proxy tx [0x6e351fae9368c890ebc108748c83a6a426910e29eb459ebf4e7475077fcc91df](https://etherscan.io/tx/0x6e351fae9368c890ebc108748c83a6a426910e29eb459ebf4e7475077fcc91df)
* `NodeDelegator` proxy [0x18169ee0ced9aa744f3cd01adc6e2eb2e8fb0087](https://etherscan.io/address/0x18169ee0ced9aa744f3cd01adc6e2eb2e8fb0087)
* `Initialize` NodeDelegator tx [0x1c318cbad3b58847d8858ac15ba25b164b5f84572a6d2fe2fab7cd693bed4af7](https://etherscan.io/tx/0x1c318cbad3b58847d8858ac15ba25b164b5f84572a6d2fe2fab7cd693bed4af7)

- [x] Delete API Key of Prime's Relayer

- [x] Verify the NodeDelegator implementation contract on Etherscan

    * [x] Check the proxy contract is already be verified
    * [x] verify the `NodeDelegator` implementation contract
    * [x] link the proxy contract to implemenation in Etherscan

```
npx hardhat verify --network mainnet 0x7D18405358c52acB3d7c8d2226C1B2e0379c1EFD 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2
```

- [x] Update the `NodeDelegator` proxy address

Update the native staking node delegator address in `Addresses.sol` and `addresses.js`

- [x] Comment out the deploy of the new NodeDelegator contract which was used by the for tests in the `DeployNativeETH` deploy script `10_deployNativeETH.s.sol`.
 
```
//  newNodeDelegator2 = NodeDelegatorLib.deployInit(1);
newNodeDelegator2 = NodeDelegator(payable(Addresses.NODE_DELEGATOR_NATIVE_STAKING));
```

- [x] Create a new SSV validator on mainnet for fork testing

The new validator will use the new EigenPod address.
* use P2P's [Create SSV Request](https://docs.p2p.org/reference/ssv-request-create) API
* Select the prod base URL
* Enter the prod bearer token
* Use the following body parameters
  * Generate a new UUID  https://www.uuidgenerator.net/ eg 
  * `validatorsCount` 1
  * `withdrawalAddress` the EigenPod for the new NodeDelegator proxy 0x42791AA09bF53b5D2c0c74ac948e74a66A2fe35e
  * `feeRecipientAddress` is the new NodeDelegator proxy 0x18169Ee0CED9AA744F3CD01Adc6E2EB2E8FB0087
  * `ssvOwnerAddress` is the new NodeDelegator proxy 0x18169Ee0CED9AA744F3CD01Adc6E2EB2E8FB0087
  * `type` is `without-encrypt-key`
  * `operationPeriodInDays` is 30

Add new SSV validator details to fork test.

uuid: 603e94c3-a0bd-4476-931d-a257ce5e5675
Public key: 0x873a2ca88b927811a0aca4998899802c10cc04cea344ddbf6682ea9b08890af131c0c708512ac631fa13a0cf6c3afa52

- [x] Run the fork tests against a local forked node

In one terminal

```
make node-fork
```

In another terminal

```
make fork-test
```

- [x] Test the contract deploy script against a local fork

Start a local Anvil node that is a fork of mainnet

```
make node-fork
```

Run the deploy script against the local fork

```bash
make deploy-native-fork 
```

- [x] Run the contract deploy script

Make sure the `MAINNET_RPC_URL` and `ETHERSCAN_API_KEY` environment variables are set in the `.env` file.

```bash
make deploy-native-mainnet
```

Deployment txs
* LRTDepositPool [0xb88c7be0f02e0844b7d57ec0a2f136871d529f9e7ce39cb4d3edc525b860e31b](https://etherscan.io/tx/0xb88c7be0f02e0844b7d57ec0a2f136871d529f9e7ce39cb4d3edc525b860e31b)
* NodeDelegator [0x030635a6e751bdb7f079afc5d8ca689cc4f2b620364ee88b2be533958827648b](https://etherscan.io/tx/0x030635a6e751bdb7f079afc5d8ca689cc4f2b620364ee88b2be533958827648b)
* WETHPriceOracle [0x89e3bed91b974bdea6feff5b21123b05d3ee646c6ed4bd685f1b72f3c72c5ede](https://etherscan.io/tx/0x89e3bed91b974bdea6feff5b21123b05d3ee646c6ed4bd685f1b72f3c72c5ede)
* Create WETHPriceOracle proxy  [0x4adf0d7551e1be25da5d247239e1dea4e0ea301ebfccce00827da727c6419ade](https://etherscan.io/tx/0x4adf0d7551e1be25da5d247239e1dea4e0ea301ebfccce00827da727c6419ade)
* PrimeZapper [0x4d4edaa334bcf4d461619eaeb31113df7c4e9750efebf88fd007d80931109f09](https://etherscan.io/tx/0x4d4edaa334bcf4d461619eaeb31113df7c4e9750efebf88fd007d80931109f09)

- [x] Check the contracts on Etherscan

    * [x] Check the contracts were verified
    * [x] Link the proxy to the implementation
    * [x] Check the constants and immutables have been set correctly
    * [x] Check the storage variables have been initialized correctly

Check the implementation contracts for `LRTDepositPool` and `NodeDelegator`.
Check the proxy and implementation contracts for `WETHPriceOracle`.
Check the proxy and implementation contracts for the new `NodeDelegator`.

- [x] Update the contract address in the README

* Native Staking NodeDelegator implementation
* Native Staking NodeDelegator proxy
* LRTDepositPool implementation
* LST NodeDelegator implementation
* WETHPriceOracle implementation
* WETHPriceOracle proxy
* PrimeZapper

- [x] git commit and push changes

- [x] Verify contract on [Sourcify](https://sourcify.dev/#/verifier)

- [x] Raise multisig transaction to upgrade and configure the contracts in  3 of 7 multisig wallet [0xEc574b7faCEE6932014EbfB1508538f6015DCBb0](https://app.safe.global/home?safe=eth:0xEc574b7faCEE6932014EbfB1508538f6015DCBb0)

    1. Call `upgrade` on ProxyAdmin [0xF83cacA1bC89e4C7f93bd17c193cD98fEcc6d758](https://etherscan.io/address/0xF83cacA1bC89e4C7f93bd17c193cD98fEcc6d758) with params:
        a. Deposit Pool proxy [0xA479582c8b64533102F6F528774C536e354B8d32](https://etherscan.io/address/0xA479582c8b64533102F6F528774C536e354B8d32)
        b. new LRTDepositPool implementation [0xC059Ce5a024f25Dc90f2f5C852b4dcc00f316262](https://etherscan.io/address/0xC059Ce5a024f25Dc90f2f5C852b4dcc00f316262)
    2. Call `upgrade` on ProxyAdmin [0xF83cacA1bC89e4C7f93bd17c193cD98fEcc6d758](https://etherscan.io/address/0xF83cacA1bC89e4C7f93bd17c193cD98fEcc6d758) with params:
        a. old NodeDelegator proxy [0x8bBBCB5F4D31a6db3201D40F478f30Dc4F704aE2](https://etherscan.io/address/0x8bBBCB5F4D31a6db3201D40F478f30Dc4F704aE2)
        b. new NodeDelegator implementation [0xAC49836f90E37B8Ab7db5de0e5Bec0b1621451F3](https://etherscan.io/address/0xAC49836f90E37B8Ab7db5de0e5Bec0b1621451F3)
    3. Call `addNewSupportedAsset` on Config proxy [0xF879c7859b6DE6FAdaFB74224Ff05b16871646bF](https://etherscan.io/address/0xF879c7859b6DE6FAdaFB74224Ff05b16871646bF) with params:
        a. WETH token [0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2](https://etherscan.io/token/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2)
        b. maxDeposits 100_000 ether
    4. Call `setToken` on Config proxy [0xF879c7859b6DE6FAdaFB74224Ff05b16871646bF](https://etherscan.io/address/0xF879c7859b6DE6FAdaFB74224Ff05b16871646bF) with params:
        a. keccak256("WETH_TOKEN") `0x641571901ab14f599ca9232149cf699f3b3f2573091ef1e19cd524b0542618c9`
        a. WETH token [0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2](https://etherscan.io/token/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2)
    5. Call `updatePriceOracleFor` on Oracle proxy [0xA755c18CD2376ee238daA5Ce88AcF17Ea74C1c32](https://etherscan.io/address/0xA755c18CD2376ee238daA5Ce88AcF17Ea74C1c32) with params:
        a. WETH token [0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2](https://etherscan.io/token/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2)
        b. new WETH Oracle proxy [0x2772337eD6cC93CB440e68607557CfCCC0E6b700](https://etherscan.io/token/0x2772337eD6cC93CB440e68607557CfCCC0E6b700)
    6. Call `setContract` on Config proxy [0xF879c7859b6DE6FAdaFB74224Ff05b16871646bF](https://etherscan.io/address/0xF879c7859b6DE6FAdaFB74224Ff05b16871646bF) with params:
        a. keccak256("EIGEN_POD_MANAGER") `0xfa35f8e3786b5a503b997a59c721169d947268d05decc8725b4881abe793c5e7`
        a. EigenPodManager [0x91E677b07F7AF907ec9a428aafA9fc14a0d3A338](https://etherscan.io/token/0x91E677b07F7AF907ec9a428aafA9fc14a0d3A338)
    7. Call `setContract` on Config proxy [0xF879c7859b6DE6FAdaFB74224Ff05b16871646bF](https://etherscan.io/address/0xF879c7859b6DE6FAdaFB74224Ff05b16871646bF) with params:
        a. keccak256("SSV_TOKEN") `0x6743d413553f874d7a6c479fb98f33e5ebd744d8b81a80e0234acca1e3b1ff15`
        a. SSV Token [0x9D65fF81a3c488d585bBfb0Bfe3c7707c7917f54](https://etherscan.io/token/0x9D65fF81a3c488d585bBfb0Bfe3c7707c7917f54)
    8. Call `setContract` on Config proxy [0xF879c7859b6DE6FAdaFB74224Ff05b16871646bF](https://etherscan.io/address/0xF879c7859b6DE6FAdaFB74224Ff05b16871646bF) with params:
        a. keccak256("SSV_NETWORK") `0x6d2a0d20ac2d1cb51ddf72eb96dc97e62954251d2f50054ed655b7678bdaf119`
        a. SSV Network [0xDD9BC35aE942eF0cFa76930954a156B3fF30a4E1](https://etherscan.io/token/0xDD9BC35aE942eF0cFa76930954a156B3fF30a4E1)
    9. Call `approveSSV` on new NodeDelegator proxy [0x18169ee0ced9aa744f3cd01adc6e2eb2e8fb0087](https://etherscan.io/address/0x18169ee0ced9aa744f3cd01adc6e2eb2e8fb0087)
    10. Call `createEigenPod` on new NodeDelegator proxy [0x18169ee0ced9aa744f3cd01adc6e2eb2e8fb0087](https://etherscan.io/address/0x18169ee0ced9aa744f3cd01adc6e2eb2e8fb0087)
    11. Call `transfer` on SSV Tokens [0x9D65fF81a3c488d585bBfb0Bfe3c7707c7917f54](https://etherscan.io/token/0x9D65fF81a3c488d585bBfb0Bfe3c7707c7917f54) with params:
        a. new NodeDelegator proxy [0x18169ee0ced9aa744f3cd01adc6e2eb2e8fb0087](https://etherscan.io/address/0x18169ee0ced9aa744f3cd01adc6e2eb2e8fb0087)
        b. 10e18
    12. Call `updateAssetDepositLimit` on Config proxy [0xF879c7859b6DE6FAdaFB74224Ff05b16871646bF](https://etherscan.io/address/0xF879c7859b6DE6FAdaFB74224Ff05b16871646bF) with params:
        a. OETH [0x856c4Efb76C1D1AE02e20CEB03A2A6a08b0b8dC3](https://etherscan.io/token/0x856c4Efb76C1D1AE02e20CEB03A2A6a08b0b8dC3)
        b. depositLimit zero
    13. Call `updateAssetDepositLimit` on Config proxy [0xF879c7859b6DE6FAdaFB74224Ff05b16871646bF](https://etherscan.io/address/0xF879c7859b6DE6FAdaFB74224Ff05b16871646bF) with params:
        a. sfrxETH [0xac3E018457B222d93114458476f3E3416Abbe38F](https://etherscan.io/token/0xac3E018457B222d93114458476f3E3416Abbe38F)
        b. depositLimit zero
    14. Call `updateAssetDepositLimit` on Config proxy [0xF879c7859b6DE6FAdaFB74224Ff05b16871646bF](https://etherscan.io/address/0xF879c7859b6DE6FAdaFB74224Ff05b16871646bF) with params:
        a. mETH [0xd5F7838F5C461fefF7FE49ea5ebaF7728bB0ADfa](https://etherscan.io/token/0xd5F7838F5C461fefF7FE49ea5ebaF7728bB0ADfa)
        b. depositLimit zero
    15. Call `updateAssetDepositLimit` on Config proxy [0xF879c7859b6DE6FAdaFB74224Ff05b16871646bF](https://etherscan.io/address/0xF879c7859b6DE6FAdaFB74224Ff05b16871646bF) with params:
        a. stETH [0xae7ab96520DE3A18E5e111B5EaAb095312D7fE84](https://etherscan.io/token/0xae7ab96520DE3A18E5e111B5EaAb095312D7fE84)
        b. depositLimit zero
    16. Call `updateAssetDepositLimit` on Config proxy [0xF879c7859b6DE6FAdaFB74224Ff05b16871646bF](https://etherscan.io/address/0xF879c7859b6DE6FAdaFB74224Ff05b16871646bF) with params:
        a. rETH [0xae78736Cd615f374D3085123A210448E74Fc6393](https://etherscan.io/token/0xae78736Cd615f374D3085123A210448E74Fc6393)
        b. depositLimit zero
    17. Call `updateAssetDepositLimit` on Config proxy [0xF879c7859b6DE6FAdaFB74224Ff05b16871646bF](https://etherscan.io/address/0xF879c7859b6DE6FAdaFB74224Ff05b16871646bF) with params:
        a. swETH [0xf951E335afb289353dc249e82926178EaC7DEd78](https://etherscan.io/token/0xf951E335afb289353dc249e82926178EaC7DEd78)
        b. depositLimit zero
    18. Call `updateAssetDepositLimit` on Config proxy [0xF879c7859b6DE6FAdaFB74224Ff05b16871646bF](https://etherscan.io/address/0xF879c7859b6DE6FAdaFB74224Ff05b16871646bF) with params:
        a. ETHx [0xA35b1B31Ce002FBF2058D22F30f95D405200A15b](https://etherscan.io/token/0xA35b1B31Ce002FBF2058D22F30f95D405200A15b)
        b. depositLimit zero
    19. Call `addNodeDelegator` on Deposit Pool proxy [0xA479582c8b64533102F6F528774C536e354B8d32](https://etherscan.io/address/0xA479582c8b64533102F6F528774C536e354B8d32) with params:
        a. new NodeDelegator proxy [0x18169ee0ced9aa744f3cd01adc6e2eb2e8fb0087](https://etherscan.io/address/0x18169ee0ced9aa744f3cd01adc6e2eb2e8fb0087)

- [x] Sign multisig transaction

Requires 3 of 7

- [x] Execute multisig transaction

Execution tx [0x60196549b59ac65d6571c22dafb8919285343daf2a0ba95a12aebb999c39dad1](https://etherscan.io/tx/0x60196549b59ac65d6571c22dafb8919285343daf2a0ba95a12aebb999c39dad1)

- [x] Add the `EIGEN_POD` address from the `createEigenPod` call to the new `NodeDelegator`

Add to the `Addresses.sol` and `addresses.js` files.

- [x] Added the block number to deploy script

Set the `deployBlockNum` in the constructor of the `DeployNativeETH` script to the block the multisig tx was executed in.

- [x] Regenerate contract diagrams for upgraded contracts
- [x] git commit and push changes
- [x] Request Dune decoding of the upgraded contracts
- [x] Fork Test the upgraded contracts and configuration
- [x] Raise multisig transaction to unpause WETH deposits in 3 of 7 multisig wallet [0xEc574b7faCEE6932014EbfB1508538f6015DCBb0](https://app.safe.global/home?safe=eth:0xEc574b7faCEE6932014EbfB1508538f6015DCBb0)

    1. Call `unpause` on Deposit Pool proxy [0xA479582c8b64533102F6F528774C536e354B8d32](https://etherscan.io/address/0xA479582c8b64533102F6F528774C536e354B8d32)
    2. Transfer 90 SSV tokens [0x9D65fF81a3c488d585bBfb0Bfe3c7707c7917f54](https://etherscan.io/token/0x9D65fF81a3c488d585bBfb0Bfe3c7707c7917f54) to the Native Staking NodeDelegator [0x18169ee0ced9aa744f3cd01adc6e2eb2e8fb0087](https://etherscan.io/address/0x18169ee0ced9aa744f3cd01adc6e2eb2e8fb0087)
    3. deposit 32 ether via the PrimeZapper [0x3cf4Db4c59dCB082d1A9719C54dF3c04Db93C6b7](https://etherscan.io/address/0x3cf4Db4c59dCB082d1A9719C54dF3c04Db93C6b7)

- [x] Deploy new Defender Action to transfer WETH to the Native Staking NodeDelegator

New Defender Action is [Prime - transfer WETH to Native Staking NodeDelegator](https://defender.openzeppelin.com/v2/#/actions/automatic/d990c176-897d-4739-8f20-563fbacf11b0)

- [x] Sign multisig transaction

Requires 3 of 7

- [x] Execute multisig transaction

Execution tx [0xa35f5c4f3553eef10af7dda863e5d4d65be4572a26c35b2c16d49f63d636deec](https://etherscan.io/tx/0xa35f5c4f3553eef10af7dda863e5d4d65be4572a26c35b2c16d49f63d636deec)

- [x] Post deploy verification testing

   - [x] transfer 32 ETH to native NodeDelegator [0x51e5f48ffe5ba72b1d9c8f224953d03cb65338ec54474d93dab087cc10efd1a3](https://etherscan.io/tx/0x51e5f48ffe5ba72b1d9c8f224953d03cb65338ec54474d93dab087cc10efd1a3)
   - [x] register validator [0x11e444745973662e620971d4cf7b86f75c0f2a0662b8c4d11ab714817f30b227](https://etherscan.io/tx/0x11e444745973662e620971d4cf7b86f75c0f2a0662b8c4d11ab714817f30b227)
   - [x] stake to validator [0x6f96d258c7a5eb7e0c21267b21e4d24dca04136da424a14cfdbb0b4f6f542aea](https://etherscan.io/tx/0x6f96d258c7a5eb7e0c21267b21e4d24dca04136da424a14cfdbb0b4f6f542aea)
 
validator https://beaconcha.in/validator/ab62adce2d14bfff0dc555126e0482a9b08e4fe71a152b1b4f858ef163273bfb8a7059e691d4840bc5295be3ec47e2ae#deposits

- [ ] Merge this PR

### CODE REVIEW

**Comment by DanielVF** [comment]
⚫ I notice that the deploy script transfers 20 SSV tokens to the node, but the actual created governance action only transferred 10. Is there a reason for doing ten?

**Review by DanielVF — APPROVED** [review]
I have verified the following:
```
- [x] All deployed contracts are listed in the deploy PR's description
- [x] Deployed contract's verified code (and all dependencies) match the code in master
- [x] The transactions that interacted with the newly deployed contracts match the deploy script.
- [x] Governance proposal matches the deploy script (Mostly, see note above)
```

**Comment by sparrowDom** [comment]
I've validated that:
- all the deployed contract's code matches the one in main branch
- the transactions from deploy script match the ones in the governance proposal and have the correct values

On nitpick I noticed (relates to the same SSV token transfer that Daniel also mentioned), is that I would expect the transfer of the tokens to be the last transaction in the governance proposal and not be somewhere in the middle. (aside from having 20 SSV tokens instead of 10). I assume you've changed that afterwards the submission of the governance proposal.

**Comment by sparrowDom** [comment]
Also just curious why did the defender relayer needed to deploy the native staking node delegator (as opposed to being part of the forge deploy script)?

**Review by sparrowDom — APPROVED** [review]

**Comment by naddison36** [comment]
> Also just curious why did the defender relayer needed to deploy the native staking node delegator (as opposed to being part of the forge deploy script)?

Good question. It's because of the way the SSV rewards work. They go to the deployer of the contract which we didn't want to be the deployer account used to run the forge deploy script.

**Comment by naddison36** [comment]
> ⚫ I notice that the deploy script transfers 20 SSV tokens to the node, but the actual created governance action only transferred 10. Is there a reason for doing ten?

we have 100 SSV to transfer. I'll do the rest in the next multsig that does the unpause. I wanted to limit the amount of SSV used in case we had to redeploy the NodeDelegator

**Pull request merged**
