### PR TITLE
NodeDelegator changes

### PR DESCRIPTION
**Pull request by naddison36**
# Contract changes

* Removed `verifyWithdrawalCredentials` from `NodeDelegator` as anyone can call `verifyWithdrawalCredentialsAndBalance` on the `EigenPod` with the validator proofs.
* Added `whenNotPaused` modifier on `onlyLRTOperator` functions on the `NodeDelegator`
* Added `initiateWithdrawRewards` and `claimRewards` functions to `NodeDelegator`

### CODE REVIEW

**Comment by DanielVF** [comment]
`verifyWithdrawalCredentials` appears to be pod owner only. It's the method that "activates" the validator as far as I can see.

image

When searching the eigenlayer contracts, repo I can't find the mentioned `verifyWithdrawalCredentialsAndBalance` that anyone can call?

**Comment by naddison36** [comment]
> `verifyWithdrawalCredentials` appears to be pod owner only. It's the method that "activates" the validator as far as I can see.
> 
> image
> When searching the eigenlayer contracts, repo I can't find the mentioned `verifyWithdrawalCredentialsAndBalance` that anyone can call?

you are correct. I must have been looking at `verifyBalanceUpdates` or `verifyAndProcessWithdrawals`.
I'll restore `verifyWithdrawalCredentials` on the NodeDelegator and test if we need to reduce `stakedButNotVerifiedEth` or not.

**Comment by naddison36** [comment]
I see the confusion now. The EigenLayer contracts are different on Mainnet and Goerli. Mainnet has EigenLayer M1  while Goerli has EigenLayer M2.

Mainnet has 
```Solidity
/**
 * @notice  This function verifies that the withdrawal credentials of the podOwner are pointed to
 * this contract. It also verifies the current (not effective) balance  of the validator.  It verifies the provided proof of the ETH validator against the beacon chain state
 * root, marks the validator as 'active' in EigenLayer, and credits the restaked ETH in Eigenlayer.
 * @param oracleBlockNumber is the Beacon Chain blockNumber whose state root the `proof` will be proven against.
 * @param validatorIndex is the index of the validator being proven, refer to consensus specs 
 * @param proofs is the bytes that prove the ETH validator's balance and withdrawal credentials against a beacon chain state root
 * @param validatorFields are the fields of the "Validator Container", refer to consensus specs 
 * for details: https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/beacon-chain.md#validator
 */
function verifyWithdrawalCredentialsAndBalance(
    uint64 oracleBlockNumber,
    uint40 validatorIndex,
    BeaconChainProofs.ValidatorFieldsAndBalanceProofs calldata proofs,
    bytes32[] calldata validatorFields
)
    external
    onlyWhenNotPaused(PAUSED_EIGENPODS_VERIFY_CREDENTIALS)
    // check that the provided `oracleBlockNumber` is after the `mostRecentWithdrawalBlockNumber`
    proofIsForValidBlockNumber(oracleBlockNumber)
{
```

While Goerli has
```Solidity
/**
 * @notice This function verifies that the withdrawal credentials of validator(s) owned by the podOwner are pointed to
 * this contract. It also verifies the effective balance  of the validator.  It verifies the provided proof of the ETH validator against the beacon chain state
 * root, marks the validator as 'active' in EigenLayer, and credits the restaked ETH in Eigenlayer.
 * @param oracleTimestamp is the Beacon Chain timestamp whose state root the `proof` will be proven against.
 * @param stateRootProof proves a `beaconStateRoot` against a block root fetched from the oracle
 * @param validatorIndices is the list of indices of the validators being proven, refer to consensus specs
 * @param validatorFieldsProofs proofs against the `beaconStateRoot` for each validator in `validatorFields`
 * @param validatorFields are the fields of the "Validator Container", refer to consensus specs
 * for details: https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/beacon-chain.md#validator
 */
function verifyWithdrawalCredentials(
    uint64 oracleTimestamp,
    BeaconChainProofs.StateRootProof calldata stateRootProof,
    uint40[] calldata validatorIndices,
    bytes[] calldata validatorFieldsProofs,
    bytes32[][] calldata validatorFields
)
    external
    onlyEigenPodOwner
    onlyWhenNotPaused(PAUSED_EIGENPODS_VERIFY_CREDENTIALS)
    // check that the provided `oracleTimestamp` is after the `mostRecentWithdrawalTimestamp`
    proofIsForValidTimestamp(oracleTimestamp)
    // ensure that caller has previously enabled restaking by calling `activateRestaking()`
    hasEnabledRestaking
{
```

**Review by DanielVF — APPROVED** [review]
Good enough to merge into the main branch.

**Pull request merged**
